ARG PARENT_IMAGE=quay.io/centos/centos:stream9

FROM ${PARENT_IMAGE}

RUN <<EOR bash -l
# Install CUDA from Spack
set -xeuo pipefail

module load spack
spack install \
  cuda target=x86_64_v3 \
  cudnn target=x86_64_v3
EOR

RUN <<EOR bash -l
# Install NCCL from Spack
set -xeuo pipefail

module load spack
spack install \
  nccl cuda_arch=75 target=x86_64_v3 \
  nccl-tests cuda_arch=75 arch=x86_64_v3
EOR

RUN <<EOR bash -l
# Install PyTorch from Spack
set -xeuo pipefail

module load spack
spack install py-torch target=x86_64_v3
spack module lmod refresh -y
EOR
