name: Build OpenHPC-based Slurm images

env:
  REGISTRY: quay.io/slinky-on-openshift
  PARENT_IMAGE: quay.io/centos/centos:stream9
  BAKE_IMPORTS: --file docker-bake.hcl --file ${{ github.event.inputs.version }}/rockylinux9/slurm.hcl --set *.args.linux_flavor=centos9-ohpc

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The slurm-cluster-operator version to build and release"
        required: true
        type: choice
        default: "25.11"
        options:
          - "25.05"
          - "25.11"
      # target:
      #   description: "the bake target"
      #   required: true
      #   type: choice
      #   default: "cuda"
      #   options:
      #     - "cuda"
      #     - "core"
  # push:
  #   branches: [ "main" ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
          verbose: true

      - name: Patch HCL flavor
        run: |
          FILE_PATH="schedmd/slurm/${{ github.event.inputs.version }}/rockylinux9/slurm.hcl"
          echo "Patching $FILE_PATH..."
          sed -i 's/linux_flavor = "rockylinux9"/linux_flavor = "centos9"/g' "$FILE_PATH"
          echo 'context = "${slurm_dir}/rockylinux9"' >> "$FILE_PATH"

      - name: Build images with docker buildx
        run: |
          cd ./schedmd/slurm
          docker buildx bake ${{ env.BAKE_IMPORTS }} --print core
          docker buildx bake ${{ env.BAKE_IMPORTS }} --progress=plain --push core

      - name: Build and Push OpenHPC Layer
        run: |
          # Define the tags created by bake (matching your format_tag logic)
          VERSION="${{ github.event.inputs.version }}"
          FLAVOR="centos9-ohpc"

          # Build on top of slurmd
          docker build
            --build-arg BASE_IMAGE=${{ env.REGISTRY }}/slurmd:${VERSION}-${FLAVOR} \
            -t ${{ env.REGISTRY }}/slurmd:${VERSION}-${FLAVOR}-ohpc \
            -f openhpc/el9/Dockerfile \
            --push .

          # Build on top of login
          docker build
            --build-arg BASE_IMAGE=${{ env.REGISTRY }}/login:${VERSION}-${FLAVOR} \
            -t ${{ env.REGISTRY }}/login:${VERSION}-${FLAVOR}-ohpc \
            -f openhpc/el9/Dockerfile \
            --push .
