name: Build OpenHPC-based Slurm images

env:
  REGISTRY: quay.io/slinky-on-openshift
  PARENT_IMAGE: quay.io/centos/centos:stream9
  BAKE_TARGET: core
  BAKE_IMPORTS: --file docker-bake.hcl --file 25.05/centos9-ohpc/slurm.hcl

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
          verbose: true

      - name: Build images with docker buildx
        run: |
          cd ./schedmd/slurm
          docker buildx bake ${{ env.BAKE_IMPORTS }} --print ${{ env.BAKE_TARGET }}
          docker buildx bake ${{ env.BAKE_IMPORTS }} --progress=plain --push ${{ env.BAKE_TARGET }}
